name: Lint Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Install linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run linter
        run: |
          golangci-lint run ./...
